### PR TITLE
Fix paste_buffer

### PR DESCRIPTION
**Pull request by Alcaro**
Credit to @lethal-click (#43)

### CODE REVIEW

**Comment by sm00th** [comment]
@Alcaro did you test this or do we need someone to do that?

**Comment by Alcaro** [comment]
I believe lethal-click tested it. I personally did not, I'm just following lethal's orders.

**Comment by lethal-click** [comment]
test was: 

using bitlbee 3.5.1, bitlbee-discord 0.4.2
set bitlbee parameters `paste_buffer = true`, `paste_buffer_delay = 50` (I'm running bitlbee on the same box as my IRC client)
paste into IRC client text containing newlines
verify in Discord native client that output showed up as a single message from me, displayed across multiple lines (same as what happens when a Discord native client writes a line containing newlines created by shift-enter)

I would certainly feel better if someone else tested this; I've been running this a few days now with no problems BUT I can't say I actually trigger the multiline stuff very often.

**Comment by sm00th** [comment]
Let's keep this around a while (a week or two), maybe someone else will be able to test this just to be sure.

Also ccing originla reporter: @tecknojock

**Pull request merged**
