### PR TITLE
Group DMs

### PR DESCRIPTION
**Pull request by arcnmx**
Group names can change easily, so this uses the ID as the bitlbee room name. Use `chat list discord` to find them, they will not be joined automatically.

Not handled: add/remove users on a `CHANNEL_UPDATE` (is that even used for group dms? I have no idea)

See also #54

### CODE REVIEW

**Comment by sm00th** [comment]
Note to self: bump plugin version after merging this.

**Comment by arcnmx** [comment]
An event for handling updates to recipients seems to be:

`{"t":"CHANNEL_RECIPIENT_REMOVE","s":_,"op":0,"d":{"user":{"username":_,"id":_,"discriminator":_,"avatar":_},"channel_id":_}}`

Presumably there's an add event as well.

**Comment by sm00th** [comment]
Sorry it took me so long to review this. Seems to be solid overall. Feature-wise adding/removing could be a really nice addon and topic could contain recepients so it is easier to find proper group dm in chat list if you have multiple, but I don't consider any of these a hard requirement for merging.

So if you have no objections I'll merge this and we can work on mentioned improvements later?

**Comment by arcnmx** [comment]
There are definitely improvements to be made, but yeah I think they can be incrementally done afterward. It's been working well enough to be useful for me. From using it these past two weeks, the main issues I've noticed so far:

- Topic definitely should be comma-separated list of recipients when null, the same way the discord UI names group chats until an explicit title is set
- Support updates to the title on `CHANNEL_UPDATE`
- Handle `CHANNEL_RECIPIENT_ADD`/`CHANNEL_RECIPIENT_REMOVE`
- The current interaction with online/offline status is kind of awkward, and users coming online need to be re-added to the channel.

**Comment by sm00th** [comment]
Agreed on all points. I am not sure about the last though, I didn't check in a while but last time I did discord wasn't very good about reporting statuses for users that are not on the same server as you. Maybe it is different with friends now though.

**Comment by arcnmx** [comment]
Yeah, actually, part of the problem seems to be that if you *do* share servers with someone, they'll QUIT when they go offline and leave the channel, and then just not come back. Friends seem to always stay online? There certainly are some improvements to be made there, but I haven't paid enough attention to it really.

**Comment by sm00th** [comment]
Friends should only stay online if both `never_offline` and `friendship_mode` are on.
But yeah, the reconnects make this issue less pressing, although I'd prefer to not have them :)

**Pull request merged**
